# Add WebRTC echo-cancel module with beamforming to PipeWire

context.modules = [
    { name = libpipewire-module-echo-cancel
      args = {
          library.name = aec/libspa-aec-webrtc
          aec.args = "beamforming=1 mic_geometry=-0.075,0,0,0.075,0,0"
      }
    }
]

# Add aec library mapping
context.spa-libs = {
    "aec.*" = aec/libspa-aec
}